### ISSUE TITLE
Devolución TP1

### ISSUE THREAD

**Issue by carlosalbertopardo** [juandematei/Nivel2-TP1#1]
Buénisimo Juan!
Se que son ejercicios chiquitos por ahora pero es una buena práctica separar los archivos de js, css y html en carpetas diferentes para esta estructurar el proyecto. Si pones el archivo base como index.html el browser cuando llegue a esa carpeta te lo abre por defecto.

También recordá que para pasar de string a number, también podes utilizar parseInt:
- https://www.w3schools.com/jsref/jsref_number.asp
- https://www.w3schools.com/jsref/jsref_parseint.asp

Saludos!

**Comment by juandematei** [comment]
Gracias! Voy a empezar a hacerlo aún en los trabajos chicos para ir acostumbrándome.
